config/routes.rb
Rails.application.routes.draw do
  namespace :public do
    get 'tags/show'
  end

  devise_for :users, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }

  devise_scope :user do
    get '/guest_login', to: 'public/sessions#guest_login', as: 'guest_login'
    post 'users/guest_sign_in', to: 'public/sessions#guest_sign_in'
    get '/users/sign_in' => 'devise/sessions#new'
  end

  scope module: :public do
    root to: "homes#top"
    get "/about", to: "homes#about", as: 'about'
    get '/mypage', to: 'users#mypage', as: 'mypage'
    get '/search', to: 'searches#search', as: 'search'
    get 'search_address', to: 'places#search_address'

    resources :users, only: [:create, :show, :edit, :update, :destroy, :index] do
      member do
        post 'follow', to: 'relationships#create'
        delete 'unfollow', to: 'relationships#destroy'
        get :followers, :following
      end
    end
    resources :tags, only: [:index, :show] do
      collection do
        get 'search', to: 'tags#search'
      end
    end  
    resources :places do
      resources :posts,only: [:new, :create]
      resource :bookmark, only: [:create, :destroy]
    end  
    resources :events do
      resources :posts, only: [:new, :create]
      resource :bookmark, only: [:create, :destroy]
    end 
    resources :posts do
      resources :reviews
      resources :comments, only: [:create, :destroy]
      resource :bookmark, only: [:create, :destroy]
    end
    resources :reviews do
      resources :comments, only: [:create, :destroy]
      resource :review_like, only: [:create, :destroy]
      resource :bookmark, only: [:create, :destroy]
    end
    resources :comments do
      resource :comment_likes, only: [:create, :destroy]
    end
    resources :bookmarks, only: :index
    resources :notifications, only: :index
  end

  # 管理者用
  devise_for :admin,path: 'admin', skip: [:registrations, :passwords], controllers: {
    sessions: 'admin/sessions'
  }

  namespace :admin do 
    root to: "dashboard#index"
    resources :users, only: [:index, :show] do
     member do
       patch :deactivate
       patch :reactivate
     end
    end 
    resources :posts, only: [:index, :show, :destroy]
    resources :reviews, only: [:index, :show, :destroy] 
    resources :tags, only: [:index, :create, :edit, :show, :update, :destroy]
  end  
end

app/views/layouts/_footer.html.erb
<footer class="footer bg-dark text-white bg-light py-3 mt-auto">
  <div class="container text-center">
    <p>© 2024 PlayMap. All rights reserved.</p>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm fixed-top py-2">
    <div class="container-fluid d-flex align-items-center px-3">

      <!-- ハンバーガー（左端） -->
      <button class="navbar-toggler mr-2" type="button" data-toggle="collapse" data-target="#navbarMenu"
        aria-controls="navbarMenu" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <!-- ロゴ -->
      <%= link_to "PlayMap", root_path, class: "navbar-brand font-weight-bold h4 text-primary mr-3" %>

      <!-- 右上アイコン群 -->
      <div class="d-flex align-items-center">
        <% if current_user %>
          <!-- 通知ベル -->
          <div class="dropdown position-relative ml-3 mr-3">
            <%= link_to notifications_path, class: "text-dark position-relative" do %>
              <i class="fa fa-bell fa-lg"></i>
              <% if unchecked_notifications_count.positive? %>
                <span class="badge badge-danger position-absolute" style="top: 0; right: 0; transform: translate(50%, -50%);">
                  <%= unchecked_notifications_count %>
                </span>
              <% end %>
            <% end %>
          </div>
        <% end %>

        <div class="dropdown position-relative mr-3">
            <%= link_to bookmarks_path, class: "text-dark position-relative" do %>
              <i class="fa-solid fa-bookmark"></i> 
            <% end %>  
        </div>
      
        <!-- 検索アイコン -->
        <button class="btn btn-link text-dark p-0" id="searchToggle">
          <i class="fas fa-search fa-lg"></i>
        </button>
      </div>

      <!-- メニュー（折りたたみ時は下にスライド） -->
      <div class="collapse navbar-collapse mt-2 mt-md-0" id="navbarMenu">
        <ul class="navbar-nav ml-auto align-items-md-center">

          <% if current_user %>
            <!-- マイページ -->
            <li class="nav-item">
              <%= link_to mypage_path, class: "nav-link d-flex align-items-center" do %>
                <i class="fas fa-user mr-2"></i> マイページ
              <% end %>
            </li>

            <!-- 一覧ドロップダウン -->
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle d-flex align-items-center" href="#" id="listDropdown"
                 role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-list mr-2"></i> 一覧
              </a>
              <div class="dropdown-menu" aria-labelledby="listDropdown">
                <%= link_to "投稿一覧", posts_path, class: "dropdown-item" %>
                <%= link_to "レビューリスト", reviews_path, class: "dropdown-item" %>
                <%= link_to "場所一覧", places_path, class: "dropdown-item" %>
                <%= link_to "イベント一覧", events_path, class: "dropdown-item" %>
                <%= link_to "ユーザーリスト", users_path, class: "dropdown-item" %>
              </div>
            </li>

            <!-- ログアウト -->
            <li class="nav-item">
              <%= link_to destroy_user_session_path, method: :delete,
                  class: "nav-link text-danger d-flex align-items-center" do %>
                <i class="fas fa-sign-out-alt mr-2"></i> ログアウト
              <% end %>
            </li>
          <% else %>
            <!-- 未ログイン時 -->
            <li class="nav-item mr-2">
              <%= link_to new_user_registration_path, class: "btn btn-outline-primary" do %>
                <i class="fas fa-user-plus mr-1"></i> 新規登録
              <% end %>
            </li>
            <li class="nav-item mr-2">
              <%= link_to new_user_session_path, class: "btn btn-outline-primary" do %>
                <i class="fas fa-sign-in-alt mr-1"></i> ログイン
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to guest_login_path, class: "btn btn-outline-secondary" do %>
                <i class="fa-regular fa-circle-user"></i> ゲストログイン
              <% end %>
            </li>
          <% end %>

        </ul>
      </div>
    </div>
  </nav>

  <!-- 検索フォーム -->
  <div id="searchFormWrapper" class="bg-light px-3 py-2 shadow-sm position-fixed w-100 d-none"
       style="top: 60px; z-index: 1050;">
    <%= render 'public/shared/search_form' %>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PlayMap</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+JP:wght@400;700&display=swap" rel="stylesheet">
    <link href="https://unpkg.com/aos@2.3.1/dist/aos.css" rel="stylesheet">

    <!-- CDN Scripts -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.jpostal/2.13.0/jquery.jpostal.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/raty/2.9.0/jquery.raty.min.js"></script>

    <script src="https://unpkg.com/aos@2.3.1/dist/aos.js"></script>

    <!-- CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/raty/2.7.1/jquery.raty.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/aos/2.3.4/aos.css">

    <!-- JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/aos/2.3.4/aos.js"></script>
    <script src="https://kit.fontawesome.com/e070c49e1d.js" crossorigin="anonymous"></script>

    <!-- Webpacker -->
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- select2-->
    <%= stylesheet_link_tag "https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" %>
    <%= javascript_include_tag "https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js" %>
    
    <!-- Maps API Key -->
    <!-- AOS  -->
    <script>
      window.MAPS_API_KEY = "<%= ENV['MAPS_API_KEY'] %>";

      document.addEventListener('turbolinks:load', function() {
        AOS.init({ 
          duration: 1000, 
          once: true,
          easing: 'ease-out-quad' 
        });
      });
    </script>

  </head>

  <body>
    <div class="d-flex flex-column min-vh-100">

      <% if controller_path.start_with?("admin/") %>
        <!-- 管理者用ナビゲーション -->
        <nav class="navbar admin-navbar navbar-expand-lg navbar-light">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <span class="navbar-text mr-3">ようこそ、管理者さん！</span>
            </li>
            <li class="nav-item">
              <%= link_to "ダッシュボード", admin_root_path, class: "btn btn-outline-primary mx-3" %>
            </li>
            <li class="nav-item">
              <%= link_to "ユーザー管理", admin_users_path, class: "btn btn-outline-secondary mx-3" %>
            </li>
            <li class="nav-item">
              <%= link_to "投稿管理", admin_posts_path, class: "btn btn-outline-secondary mx-3" %>
            </li>
            <li class="nav-item">
              <%= link_to "レビュー管理", admin_reviews_path, class: "btn btn-outline-secondary mx-3" %>
            </li>
            <li class="nav-item">
              <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: "btn btn-outline-danger mx-3" %>
            </li>
          </ul>
        </nav>
      <% else %>
        <%= render 'layouts/header' %>
      <% end %>

      <!-- 戻るボタン -->
      <span id="back-button">
        <%= render partial: "public/shared/back_button", locals: { back_path: request.referer } %>
      </span>

      <div id="flash-container" class="position-fixed top-0 end-0 p-3" style="z-index: 1055;">
        <div id="flash">
        <%= render 'public/shared/flash' %>
        </div>
      </div>

     
      
      <main class="flex-grow-1">
        <%= yield %>
      </main>

      <span id="page-top">
        <a href="#"><i class="fa-solid fa-angle-up"></i></a>
      </span>

      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>